<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UpdateItem.aspx.cs" Inherits="OnlineShoping.UpdateItem" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>::ManagementPage</title>
   <style>
     #m{
       height:100px;
       position:fixed;
       width:1510px;
       margin-left:-15px;
       margin-top:-10px;

      
        }
        
        .auto-style1 {
            width: 100%;
        }a{
             text-decoration:none;
             text-decoration-color:aqua;
             color:silver;
         }
          .auto-style1 {
            width: 100%;
        }
        #TextArea1 {
            width: 284px;
        }
        #des {
            width: 285px;
        }
    
       #descr {
           width: 282px;
       }
    
       .auto-style2 {
           width: 867px;
       }
       .auto-style3 {
           width: 867px;
           height: 86px;
       }
       .auto-style4 {
           width: 987px;
       }
    
   </style>
</head>
<body style="background-color:silver">
    <form  runat="server">
      <div  id="m" style="background-color: #333333">
     <div id="in">
         <table cellpadding="10px">
             <tr>
            <td><a href="Admin.aspx">
<img src="Content/images/logo-sylifyd.png" /></a>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <img src="Content/images/header-cod.png" /></td>
             <td>
                 <asp:Label ID="user" runat="server" Text="" ForeColor="White"></asp:Label></td>
                 <td>
                     <asp:Menu ID="Menu1" runat="server" BackColor="#333333" DynamicHorizontalOffset="2"
                          Font-Names="Verdana" Font-Size="0.8em" 
                         ForeColor="white" StaticSubMenuIndent="10px" Orientation="Horizontal">
                         <DynamicHoverStyle BackColor="#333333" ForeColor="White" />
                         <DynamicMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
                         <DynamicMenuStyle BackColor="#333333" />
                         <DynamicSelectedStyle BackColor="#333333" />
                         <Items>
                    <asp:MenuItem Text="My Account" Value="My Account">
                        <asp:MenuItem Text="ViewUsers" Value="ViewUsers"  NavigateUrl="ViewUsers.aspx"></asp:MenuItem>
                        <asp:MenuItem Text="SignOut" Value="SignOut"  NavigateUrl="LogIn.aspx"></asp:MenuItem>
                    </asp:MenuItem>
                </Items>
                <StaticHoverStyle BackColor="#7C6F57" ForeColor="White" />
                <StaticMenuItemStyle HorizontalPadding="5px" VerticalPadding="2px" />
                <StaticSelectedStyle BackColor="#5D7B9D" />
               </asp:Menu></td>
                       <td ><a href="Adminhome.aspx" style="font-weight:800;color:white" >Add Item</a></td>
                         <td><a href="UpdateItem.aspx" style="font-weight:800;color:white" >Update Item/Delete Item</a></td>
                         <td ><a href="ViewOrder.aspx" style="font-weight:800;color:white">View Orders</a></td>
                         
                       
                   </tr>
                </table>
               
             
              </div></div> <br /><br /><br /><br /><br /><br />
         
          <h1 style="margin-left:100px; font-style:italic;color:aliceblue">
              HERE YOU CAN UPDATE/DELETE YOUR PRODUCT::</h1>
        <div style="margin-left:100PX">   
    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False"
            DataKeyNames="ID,Color,Size" DataSourceID="SqlDataSource2" CellPadding="3" Width="1073px" SelectedRowStyle-HorizontalAlign="Justify" 
           AllowPaging="True" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" >
           <Columns>
               <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" InsertVisible="False" ReadOnly="True" />
               <asp:BoundField DataField="Name" SortExpression="Name" ItemStyle-Width="270" HeaderText="Name" >
               <ItemStyle Width="270px" />
               </asp:BoundField>
             
               <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
               <asp:BoundField DataField="ProductDescription" HeaderText="ProductDescription" SortExpression="ProductDescription" />
               <asp:BoundField DataField="Color" HeaderText="Color" ReadOnly="True" SortExpression="Color" />
               <asp:BoundField DataField="Size" HeaderText="Size" ReadOnly="True" SortExpression="Size" />
               <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
             
           </Columns>
           <FooterStyle BackColor="White" ForeColor="#000066" />
           <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
           <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left"  />
           <RowStyle ForeColor="#000066" />
           <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" HorizontalAlign="Justify" />
           <SortedAscendingCellStyle BackColor="#F1F1F1" />
           <SortedAscendingHeaderStyle BackColor="#007DBB" />
           <SortedDescendingCellStyle BackColor="#CAC9C9" />
           <SortedDescendingHeaderStyle BackColor="#00547E" />
          
       </asp:GridView>
       <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ 
           ConnectionStrings:OnlineShopingConnectionString7 %>" SelectCommand="SELECT * FROM [Item]"
           UpdateCommand="Update Item SET Name=@Name,Quantity=@Quantity,Size=@Size, ProductDescription=@ProductDescription
           ,Price=@Price WHERE ID=@ID" 
           DeleteCommand="Delete  FROM [Item] WHERE ID=@ID"></asp:SqlDataSource>
       <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$
            ConnectionStrings:OnlineShopingConnectionString6 %>" 
           SelectCommand="SELECT * FROM [Item]"></asp:SqlDataSource>
    
       </div>

    </form>
</body>
</html>

